default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: planetariyum_development

test:
  <<: *default
  database: planetariyum_test

production:
  <<: *default
  database: planetariyum_production
  username: planetariyum
  password: <% ENV["planetariyumbase"] %>